=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/XML_Parser/input.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="bodyType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Cuboid"/>
            <xsd:enumeration value="Tetrahedron"/>
            <xsd:enumeration value="Sphere"/>
            <xsd:enumeration value="Membrane"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="calcType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="LJ"/>
            <xsd:enumeration value="G"/>
            <xsd:enumeration value="smoothedLJ"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="particleContainerType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="directSum"/>
            <xsd:enumeration value="linkedCell"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="yesNo">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="yes"/>
            <xsd:enumeration value="no"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="parallelType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="notParallel"/>
            <xsd:enumeration value="first"/>
            <xsd:enumeration value="second"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="boundaryCondition">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="outflowType"/>
            <xsd:enumeration value="reflectingType"/>
            <xsd:enumeration value="betterReflectingType"/>
            <xsd:enumeration value="periodicType"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="dimensionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="2D"/>
            <xsd:enumeration value="3D"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="bodyState">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="fixed"/>
            <xsd:enumeration value="moving"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="thermostatType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="regular"/>
            <xsd:enumeration value="onlyFluid"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="gravDirectionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="x"/>
            <xsd:enumeration value="y"/>
            <xsd:enumeration value="z"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="generalParams">
        <xsd:sequence>
            <xsd:element name="t_end" type="xsd:double"/>
            <xsd:element name="delta_t" type="xsd:double"/>
            <xsd:element name="writeFrequency" type="xsd:int"/>
            <xsd:element name="dimensionType" type="dimensionType"/>
            <xsd:element name="parallelType" type="parallelType"/>

            <xsd:element name="g_grav" type="xsd:double"/>
            <xsd:element name="useGravity" type="yesNo"/>
            <xsd:element name="gravDirection" type="gravDirectionType"/>

            <xsd:element name="calcType" type="calcType"/>
            <xsd:element name="baseNameOutputFiles" type="xsd:string"/>
            <xsd:element name="cutoffRadius" type="xsd:double"/>
            <xsd:element name="gravInput" type="xsd:string"/>

            <xsd:element name="loadCheckpoint" type="yesNo"/>
            <xsd:element name="makeCheckpoint" type="yesNo"/>
            <xsd:element name="pathInCheckpoint" type="xsd:string"/>
            <xsd:element name="pathOutCheckpoint" type="xsd:string"/>

            <xsd:element name="domainSizeX" type="xsd:double"/>
            <xsd:element name="domainSizeY" type="xsd:double"/>
            <xsd:element name="domainSizeZ" type="xsd:double"/>

            <xsd:element name="useThermostat" type="yesNo"/>
            <xsd:element name="thermostatType" type="thermostatType"/>
            <xsd:element name="useBrownianMotion" type="yesNo"/>
            <xsd:element name="T_init" type="xsd:double"/>
            <xsd:element name="T_target" type="xsd:double"/>
            <xsd:element name="delta_T" type="xsd:double"/>
            <xsd:element name="n_thermostat" type="xsd:double"/>

            <xsd:element name="useVelDensProfiling" type="yesNo"/>
            <xsd:element name="numberOfBins" type="xsd:int"/>
            <xsd:element name="pathToAnalysisFolder" type="xsd:string"/>

            <xsd:element name="crystallization_r_c" type="xsd:double"/>
            <xsd:element name="crystallization_r_l" type="xsd:double"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="boundaryConditions">
        <xsd:sequence>
            <xsd:element name="top" type="boundaryCondition"/>
            <xsd:element name="right" type="boundaryCondition"/>
            <xsd:element name="bottom" type="boundaryCondition"/>
            <xsd:element name="left" type="boundaryCondition"/>
            <xsd:element name="front" type="boundaryCondition"/>
            <xsd:element name="back" type="boundaryCondition"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="particlesLJ">
        <xsd:sequence>
            <xsd:element name="body" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="bodyType" type="bodyType"/>
                        <xsd:element name="position" type="xsd:string"/>
                        <xsd:element name="velocity" type="xsd:string"/>
                        <xsd:element name="objectSpecificFormat" type="xsd:string"/>
                        <xsd:element name="epsilon" type="xsd:double"/>
                        <xsd:element name="mass" type="xsd:double"/>
                        <xsd:element name="rho" type="xsd:double"/>
                        <xsd:element name="h" type="xsd:double"/>
                        <xsd:element name="bodyState" type="bodyState"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="input">
        <xsd:sequence>
            <xsd:element name="generalParams" type="generalParams"/>
            <xsd:element name="boundaryConditions" type="boundaryConditions"/>
            <xsd:element name="particlesLJ" type="particlesLJ"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="input" type="input"/>

</xsd:schema>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/XMLinputFiles/FallingDropLiquid_makeCheckpoint.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../XML_Parser/input.xsd">

    <generalParams>
        <t_end>15</t_end>
        <delta_t>0.0005</delta_t>
        <writeFrequency>100</writeFrequency>
        <dimensionType>3D</dimensionType>

        <g_grav>-12.44</g_grav>
        <useGravity>yes</useGravity>

        <calcType>LJ</calcType>
        <baseNameOutputFiles>Lennard</baseNameOutputFiles>
        <particleContainerType_p>linkedCell</particleContainerType_p>
        <cutoffRadius>3</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>no</loadCheckpoint>
        <makeCheckpoint>yes</makeCheckpoint>
        <pathInCheckpoint>Checkpoint_Files/checkpoint_FallingDropLiquid_fluid.txt</pathInCheckpoint>
        <pathOutCheckpoint>Checkpoint_Files/checkpoint_FallingDropLiquid_fluid.txt</pathOutCheckpoint>

        <domainSizeX>20</domainSizeX>
        <domainSizeY>20</domainSizeY>
        <domainSizeZ>6</domainSizeZ>

        <useThermostat>yes</useThermostat>
        <T_init>40</T_init>
        <T_target>40</T_target>
        <delta_T>2</delta_T>
        <n_thermostat>1000</n_thermostat>
    </generalParams>

    <boundaryConditions>
        <top>periodicType</top>
        <right>periodicType</right>
        <bottom>periodicType</bottom>
        <left>periodicType</left>
        <front>periodicType</front>
        <back>periodicType</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>1,1,1</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>10,10,1</objectSpecificFormat>
            <epsilon>5.0</epsilon>
            <mass>1.0</mass>
            <rho>1.2</rho>
            <h>1.2</h>
        </body>
    </particlesLJ>

</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/Tests/TestInputFiles/ThermostatHoldTempInput.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../XML_Parser/input.xsd">

    <generalParams>
        <t_end>0.01</t_end>
        <delta_t>0.0002</delta_t>
        <writeFrequency>1000</writeFrequency>
        <dimensionType>2D</dimensionType>
        <parallelType>notParallel</parallelType>

        <g_grav>-12.44</g_grav>
        <useGravity>no</useGravity>
        <gravDirection>z</gravDirection>

        <calcType>LJ</calcType>
        <baseNameOutputFiles>Lennard</baseNameOutputFiles>
        <particleContainerType>linkedCell</particleContainerType>
        <cutoffRadius>3</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>no</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint>Checkpoint_Files/checkpointIn.txt</pathInCheckpoint>
        <pathOutCheckpoint>Checkpoint_Files/checkpointOut.txt</pathOutCheckpoint>

        <domainSizeX>100</domainSizeX>
        <domainSizeY>100</domainSizeY>
        <domainSizeZ>10</domainSizeZ>

        <useThermostat>yes</useThermostat>
        <thermostatType>regular</thermostatType>
        <useBrownianMotion>no</useBrownianMotion>
        <T_init>10.0</T_init>
        <T_target>10.0</T_target>
        <delta_T>10000</delta_T>
        <n_thermostat>1</n_thermostat>
    </generalParams>

    <boundaryConditions>
        <top>betterReflectingType</top>
        <right>betterReflectingType</right>
        <bottom>betterReflectingType</bottom>
        <left>betterReflectingType</left>
        <front>betterReflectingType</front>
        <back>betterReflectingType</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>1,1,1</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>40,8,1</objectSpecificFormat>
            <epsilon>5.0</epsilon>
            <mass>1.0</mass>
            <rho>1.0</rho>
            <h>1.125</h>
            <bodyState>moving</bodyState>
        </body>

        <body>
            <bodyType>Cuboid</bodyType>
            <position>15,15,1</position>
            <velocity>0,-10,0</velocity>
            <objectSpecificFormat>8,8,1</objectSpecificFormat>
            <epsilon>5.0</epsilon>
            <mass>1.0</mass>
            <rho>1.0</rho>
            <h>1.125</h>
            <bodyState>moving</bodyState>
        </body>
    </particlesLJ>

</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/XMLinputFiles/FallingDropLiquid_loadCheckpoint.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../src/XML_Parser/input.xsd">

    <generalParams>
        <t_end>40</t_end>
        <delta_t>0.0005</delta_t>
        <writeFrequency>100</writeFrequency>
        <dimensionType>2D</dimensionType>
        <parallelType>notParallel</parallelType>

        <g_grav>-12.44</g_grav>
        <useGravity>yes</useGravity>
        <gravDirection>y</gravDirection>

        <calcType>LJ</calcType>
        <baseNameOutputFiles>FallingDrop</baseNameOutputFiles>
        <cutoffRadius>3</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>yes</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint>checkpoint_FallingDropLiquid_fluid.txt</pathInCheckpoint>
        <pathOutCheckpoint>checkpoint_FallingDropLiquid_fluid.txt</pathOutCheckpoint>

        <domainSizeX>303</domainSizeX>
        <domainSizeY>180</domainSizeY>
        <domainSizeZ>0</domainSizeZ>

        <useThermostat>no</useThermostat>
        <thermostatType>regular</thermostatType>
        <useBrownianMotion>no</useBrownianMotion>
        <T_init>40</T_init>
        <T_target>40</T_target>
        <delta_T>2</delta_T>
        <n_thermostat>1000</n_thermostat>

        <useProfiling>no</useProfiling>
        <numberOfBins>1</numberOfBins>
        <pathToAnalysisFolder>../SimulationAnalysis_Files</pathToAnalysisFolder>

        <crystallization_r_c>0</crystallization_r_c>
        <crystallization_r_l>0</crystallization_r_l>
    </generalParams>

    <boundaryConditions>
        <top>betterReflectingType</top>
        <right>betterReflectingType</right>
        <bottom>betterReflectingType</bottom>
        <left>betterReflectingType</left>
        <front>betterReflectingType</front>
        <back>betterReflectingType</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Sphere</bodyType>
            <position>150,150,0</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>20</objectSpecificFormat>
            <epsilon>1.0</epsilon>
            <mass>1.0</mass>
            <rho>1.2</rho>
            <h>1.2</h>
            <bodyState>moving</bodyState>
        </body>
    </particlesLJ>
</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/XMLinputFiles/Membrane.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../src/XML_Parser/input.xsd">

    <generalParams>
        <t_end>1000</t_end>
        <delta_t>0.01</delta_t>
        <writeFrequency>200</writeFrequency>
        <dimensionType>3D</dimensionType>
        <parallelType>first</parallelType>

        <g_grav>-0.001</g_grav>
        <useGravity>yes</useGravity>
        <gravDirection>z</gravDirection>

        <calcType>LJ</calcType>
        <baseNameOutputFiles>Membrane</baseNameOutputFiles>
        <cutoffRadius>4</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>no</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint>checkpoint_RT.txt</pathInCheckpoint>
        <pathOutCheckpoint>checkpoint_RT.txt</pathOutCheckpoint>

        <domainSizeX>148</domainSizeX>
        <domainSizeY>148</domainSizeY>
        <domainSizeZ>148</domainSizeZ>

        <useThermostat>no</useThermostat>
        <thermostatType>onlyFluid</thermostatType>
        <useBrownianMotion>no</useBrownianMotion>
        <T_init>40</T_init>
        <T_target>40</T_target>
        <delta_T>10000</delta_T>
        <n_thermostat>10</n_thermostat>

        <useProfiling>no</useProfiling>
        <numberOfBins>1</numberOfBins>
        <pathToAnalysisFolder>../SimulationAnalysis_Files</pathToAnalysisFolder>

        <crystallization_r_c>0</crystallization_r_c>
        <crystallization_r_l>0</crystallization_r_l>
    </generalParams>

    <boundaryConditions>
        <top>betterReflectingType</top>
        <right>betterReflectingType</right>
        <bottom>betterReflectingType</bottom>
        <left>betterReflectingType</left>
        <front>betterReflectingType</front>
        <back>betterReflectingType</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Membrane</bodyType>
            <position>15,15,1.5</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>n_50,50,1 r_2.2 k_300 f_0.8 p_(17,24),(17,25),(18,24),(18,25) t_150</objectSpecificFormat>
            <epsilon>1.0</epsilon>
            <mass>1.0</mass>
            <rho>1.0</rho>
            <h>2.2</h>
            <bodyState>moving</bodyState>
        </body>
    </particlesLJ>
</input>
