=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/XML_Parser/input.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="bodyType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Cuboid"/>
            <xsd:enumeration value="Tetrahedron"/>
            <xsd:enumeration value="Sphere"/>
            <xsd:enumeration value="Membrane"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="calcType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="LJ"/>
            <xsd:enumeration value="G"/>
            <xsd:enumeration value="smoothedLJ"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="particleContainerType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="directSum"/>
            <xsd:enumeration value="linkedCell"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="yesNo">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="yes"/>
            <xsd:enumeration value="no"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="parallelType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="notParallel"/>
            <xsd:enumeration value="first"/>
            <xsd:enumeration value="second"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="boundaryCondition">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="outflowType"/>
            <xsd:enumeration value="reflectingType"/>
            <xsd:enumeration value="betterReflectingType"/>
            <xsd:enumeration value="periodicType"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="dimensionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="2D"/>
            <xsd:enumeration value="3D"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="bodyState">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="fixed"/>
            <xsd:enumeration value="moving"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="thermostatType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="regular"/>
            <xsd:enumeration value="onlyFluid"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="gravDirectionType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="x"/>
            <xsd:enumeration value="y"/>
            <xsd:enumeration value="z"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="generalParams">
        <xsd:sequence>
            <xsd:element name="t_end" type="xsd:double"/>
            <xsd:element name="delta_t" type="xsd:double"/>
            <xsd:element name="writeFrequency" type="xsd:int"/>
            <xsd:element name="dimensionType" type="dimensionType"/>
            <xsd:element name="parallelType" type="parallelType"/>

            <xsd:element name="g_grav" type="xsd:double"/>
            <xsd:element name="useGravity" type="yesNo"/>
            <xsd:element name="gravDirection" type="gravDirectionType"/>

            <xsd:element name="calcType" type="calcType"/>
            <xsd:element name="baseNameOutputFiles" type="xsd:string"/>
            <xsd:element name="cutoffRadius" type="xsd:double"/>
            <xsd:element name="gravInput" type="xsd:string"/>

            <xsd:element name="loadCheckpoint" type="yesNo"/>
            <xsd:element name="makeCheckpoint" type="yesNo"/>
            <xsd:element name="pathInCheckpoint" type="xsd:string"/>
            <xsd:element name="pathOutCheckpoint" type="xsd:string"/>

            <xsd:element name="domainSizeX" type="xsd:double"/>
            <xsd:element name="domainSizeY" type="xsd:double"/>
            <xsd:element name="domainSizeZ" type="xsd:double"/>

            <xsd:element name="useThermostat" type="yesNo"/>
            <xsd:element name="thermostatType" type="thermostatType"/>
            <xsd:element name="useBrownianMotion" type="yesNo"/>
            <xsd:element name="T_init" type="xsd:double"/>
            <xsd:element name="T_target" type="xsd:double"/>
            <xsd:element name="delta_T" type="xsd:double"/>
            <xsd:element name="n_thermostat" type="xsd:double"/>

            <xsd:element name="useVelDensProfiling" type="yesNo"/>
            <xsd:element name="numberOfBins" type="xsd:int"/>
            <xsd:element name="pathToAnalysisFolder" type="xsd:string"/>

            <xsd:element name="crystallization_r_c" type="xsd:double"/>
            <xsd:element name="crystallization_r_l" type="xsd:double"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="boundaryConditions">
        <xsd:sequence>
            <xsd:element name="top" type="boundaryCondition"/>
            <xsd:element name="right" type="boundaryCondition"/>
            <xsd:element name="bottom" type="boundaryCondition"/>
            <xsd:element name="left" type="boundaryCondition"/>
            <xsd:element name="front" type="boundaryCondition"/>
            <xsd:element name="back" type="boundaryCondition"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="particlesLJ">
        <xsd:sequence>
            <xsd:element name="body" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="bodyType" type="bodyType"/>
                        <xsd:element name="position" type="xsd:string"/>
                        <xsd:element name="velocity" type="xsd:string"/>
                        <xsd:element name="objectSpecificFormat" type="xsd:string"/>
                        <xsd:element name="epsilon" type="xsd:double"/>
                        <xsd:element name="mass" type="xsd:double"/>
                        <xsd:element name="rho" type="xsd:double"/>
                        <xsd:element name="h" type="xsd:double"/>
                        <xsd:element name="bodyState" type="bodyState"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="input">
        <xsd:sequence>
            <xsd:element name="generalParams" type="generalParams"/>
            <xsd:element name="boundaryConditions" type="boundaryConditions"/>
            <xsd:element name="particlesLJ" type="particlesLJ"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="input" type="input"/>

</xsd:schema>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/Tests/TestInputFiles/CheckpointReadWriteTest_3.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../XML_Parser/input.xsd">

    <generalParams>
        <t_end>0.005</t_end>
        <delta_t>0.0001</delta_t>
        <writeFrequency>10</writeFrequency>
        <dimensionType>2D</dimensionType>
        <parallelType>notParallel</parallelType>

        <g_grav>0</g_grav>
        <useGravity>no</useGravity>
        <gravDirection>z</gravDirection>

        <calcType>LJ</calcType>
        <baseNameOutputFiles>CheckpointTest</baseNameOutputFiles>
        <particleContainerType>linkedCell</particleContainerType>
        <cutoffRadius>3</cutoffRadius>
        <gravInput></gravInput>

        <loadCheckpoint>no</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint>checkpointReadWriteTest.txt</pathInCheckpoint>
        <pathOutCheckpoint>checkpointReadWriteTest.txt</pathOutCheckpoint>

        <domainSizeX>100</domainSizeX>
        <domainSizeY>100</domainSizeY>
        <domainSizeZ>10</domainSizeZ>

        <useThermostat>no</useThermostat>
        <thermostatType>regular</thermostatType>
        <useBrownianMotion>no</useBrownianMotion>
        <T_init>0</T_init>
        <T_target>0</T_target>
        <delta_T>0</delta_T>
        <n_thermostat>1</n_thermostat>
    </generalParams>

    <boundaryConditions>
        <top>betterReflectingType</top>
        <right>betterReflectingType</right>
        <bottom>betterReflectingType</bottom>
        <left>betterReflectingType</left>
        <front>betterReflectingType</front>
        <back>betterReflectingType</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>1,1,1</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>10,2,1</objectSpecificFormat>
            <epsilon>5.0</epsilon>
            <mass>1.0</mass>
            <rho>1.0</rho>
            <h>1.125</h>
            <bodyState>moving</bodyState>
        </body>
    </particlesLJ>

</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/XMLinputFiles/RayleighTaylor_3D.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../src/XML_Parser/input.xsd">

    <generalParams>
        <t_end>100</t_end>
        <delta_t>0.0005</delta_t>
        <writeFrequency>1000</writeFrequency>
        <dimensionType>3D</dimensionType>
        <parallelType>second</parallelType>

        <g_grav>-12.44</g_grav>
        <useGravity>yes</useGravity>
        <gravDirection>y</gravDirection>

        <calcType>LJ</calcType>
        <baseNameOutputFiles>RayleighTaylor_3D</baseNameOutputFiles>
        <cutoffRadius>3.6</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>no</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint>checkpoint_RT.txt</pathInCheckpoint>
        <pathOutCheckpoint>checkpoint_RT.txt</pathOutCheckpoint>

        <domainSizeX>60</domainSizeX>
        <domainSizeY>60</domainSizeY>
        <domainSizeZ>60</domainSizeZ>

        <useThermostat>yes</useThermostat>
        <thermostatType>regular</thermostatType>
        <useBrownianMotion>yes</useBrownianMotion>
        <T_init>40</T_init>
        <T_target>40</T_target>
        <delta_T>10000</delta_T>
        <n_thermostat>1000</n_thermostat>

        <useProfiling>no</useProfiling>
        <numberOfBins>50</numberOfBins>
        <pathToAnalysisFolder>../SimulationAnalysis_Files/RayleighTaylor/</pathToAnalysisFolder>

        <crystallization_r_c>0</crystallization_r_c>
        <crystallization_r_l>0</crystallization_r_l>
    </generalParams>

    <boundaryConditions>
        <top>betterReflectingType</top>
        <right>periodicType</right>
        <bottom>betterReflectingType</bottom>
        <left>periodicType</left>
        <front>periodicType</front>
        <back>periodicType</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>0.6,0.6,0.6</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>50,20,50</objectSpecificFormat>
            <epsilon>1.0</epsilon>
            <mass>1.0</mass>
            <rho>1.2</rho>
            <h>1.2</h>
            <bodyState>moving</bodyState>
        </body>

        <body>
            <bodyType>Cuboid</bodyType>
            <position>0.6,24.6,0.6</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>50,20,50</objectSpecificFormat>
            <epsilon>1.0</epsilon>
            <mass>2.0</mass>
            <rho>1.1</rho>
            <h>1.2</h>
            <bodyState>moving</bodyState>
        </body>
    </particlesLJ>
</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/XMLinputFiles/CollisionOfTwoBodies.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../XML_Parser/input.xsd">

    <t_end>20</t_end>
    <delta_t>0.0005</delta_t>
    <calcType>LJ</calcType>
    <baseNameOutputFiles>Lennard</baseNameOutputFiles>
    <writeFrequency>100</writeFrequency>
    <gravInput></gravInput>

    <paramsLJ>
        <epsilon>5.0</epsilon>
        <mass>1.0</mass>
        <rho>1.0</rho>
        <h>1.1225</h>
        <domainSizeX>180</domainSizeX>
        <domainSizeY>90</domainSizeY>
        <domainSizeZ>1</domainSizeZ>
        <particleContainerType>2</particleContainerType>
        <cutoffRadius>3</cutoffRadius>
    </paramsLJ>

    <boundaryConditions>
        <top>1</top>
        <right>1</right>
        <bottom>1</bottom>
        <left>1</left>
        <front>1</front>
        <back>1</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>20,20,1</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>100,20,1</objectSpecificFormat>
        </body>

        <body>
            <bodyType>Cuboid</bodyType>
            <position>70,60,1</position>
            <velocity>0,-10,0</velocity>
            <objectSpecificFormat>20,20,1</objectSpecificFormat>
        </body>
    </particlesLJ>

</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/XML_Parser/input.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="input.xsd">

    <t_end>5</t_end>
    <delta_t>0.0002</delta_t>
    <calcType>LJ</calcType>
    <baseNameOutputFiles>Lennard</baseNameOutputFiles>
    <writeFrequency>10</writeFrequency>
    <gravInput>../eingabe-sonne.txt</gravInput>

    <paramsLJ>
        <epsilon>5.0</epsilon>
        <mass>1.0</mass>
        <rho>1.0</rho>
        <h>1.125</h>
    </paramsLJ>

    <boundaryConditions>
        <top>0</top>
        <right>0</right>
        <bottom>0</bottom>
        <left>0</left>
        <front>0</front>
        <back>0</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>0,0,0</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>40,8,1</objectSpecificFormat>
        </body>

        <body>
            <bodyType>Cuboid</bodyType>
            <position>15,15,0</position>
            <velocity>0,-10,0</velocity>
            <objectSpecificFormat>8,8,1</objectSpecificFormat>
        </body>
    </particlesLJ>

</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/Tests/TestInputFiles/LinkedCellsInput.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../XML_Parser/input.xsd">

    <t_end>0.002</t_end>
    <delta_t>0.001</delta_t>
    <calcType>LJ</calcType>
    <baseNameOutputFiles>LinkedCellsTest</baseNameOutputFiles>
    <writeFrequency>1</writeFrequency>
    <gravInput></gravInput>

    <paramsLJ>
        <epsilon>5.0</epsilon>
        <mass>1.0</mass>
        <rho>1.0</rho>
        <h>1.125</h>
    </paramsLJ>

    <boundaryConditions>
        <top>1</top>
        <right>1</right>
        <bottom>1</bottom>
        <left>1</left>
        <front>1</front>
        <back>1</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>0,10,0</position>
            <velocity>0,-8,0</velocity>
            <objectSpecificFormat>5,5,5</objectSpecificFormat>
        </body>

        <body>
            <bodyType>Tetrahedron</bodyType>
            <position>0,0,0</position>
            <velocity>0,3,0</velocity>
            <objectSpecificFormat>4</objectSpecificFormat>
        </body>
    </particlesLJ>

</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/XMLinputFiles/Crystallization_cooling.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../src/XML_Parser/input.xsd">

    <generalParams>
        <t_end>250</t_end>
        <delta_t>0.001</delta_t>
        <writeFrequency>500</writeFrequency>
        <dimensionType>3D</dimensionType>
        <parallelType>first</parallelType>

        <g_grav>0</g_grav>
        <useGravity>no</useGravity>
        <gravDirection>y</gravDirection>

        <calcType>smoothedLJ</calcType>
        <baseNameOutputFiles>CoolingArgon</baseNameOutputFiles>
        <cutoffRadius>2.3</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>yes</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint>checkpoint_Crystal.txt</pathInCheckpoint>
        <pathOutCheckpoint>checkpoint_Crystal.txt</pathOutCheckpoint>

        <domainSizeX>9.2</domainSizeX>
        <domainSizeY>9.2</domainSizeY>
        <domainSizeZ>9.2</domainSizeZ>

        <useThermostat>yes</useThermostat>
        <thermostatType>regular</thermostatType>
        <useBrownianMotion>yes</useBrownianMotion>
        <T_init>3.0</T_init>
        <T_target>0.5</T_target>
        <delta_T>0.00078</delta_T>
        <n_thermostat>50</n_thermostat>

        <useProfiling>yes</useProfiling>
        <numberOfBins>50</numberOfBins>
        <pathToAnalysisFolder>../SimulationAnalysis_Files/Cooling</pathToAnalysisFolder>

        <crystallization_r_c>2.3</crystallization_r_c>
        <crystallization_r_l>1.9</crystallization_r_l>
    </generalParams>

    <boundaryConditions>
        <top>periodicType</top>
        <right>periodicType</right>
        <bottom>periodicType</bottom>
        <left>periodicType</left>
        <front>periodicType</front>
        <back>periodicType</back>
    </boundaryConditions>

    <particlesLJ>
    </particlesLJ>
</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/XMLinputFiles/Gravitation.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../src/XML_Parser/input.xsd">

    <generalParams>
        <t_end>1000</t_end>
        <delta_t>0.014</delta_t>
        <writeFrequency>10</writeFrequency>
        <dimensionType>2D</dimensionType>
        <parallelType>notParallel</parallelType>

        <g_grav>0</g_grav>
        <useGravity>no</useGravity>
        <gravDirection>z</gravDirection>

        <calcType>G</calcType>
        <baseNameOutputFiles>Grav</baseNameOutputFiles>
        <cutoffRadius>0</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>no</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint></pathInCheckpoint>
        <pathOutCheckpoint></pathOutCheckpoint>

        <domainSizeX>0</domainSizeX>
        <domainSizeY>0</domainSizeY>
        <domainSizeZ>0</domainSizeZ>

        <useThermostat>no</useThermostat>
        <thermostatType>regular</thermostatType>
        <useBrownianMotion>no</useBrownianMotion>
        <T_init>0</T_init>
        <T_target>0</T_target>
        <delta_T>0</delta_T>
        <n_thermostat>0</n_thermostat>

        <useProfiling>no</useProfiling>
        <numberOfBins>1</numberOfBins>
        <pathToAnalysisFolder>../SimulationAnalysis_Files</pathToAnalysisFolder>

        <crystallization_r_c>0</crystallization_r_c>
        <crystallization_r_l>0</crystallization_r_l>
    </generalParams>

    <boundaryConditions>
        <top>outflowType</top>
        <right>outflowType</right>
        <bottom>outflowType</bottom>
        <left>outflowType</left>
        <front>outflowType</front>
        <back>outflowType</back>
    </boundaryConditions>

    <particlesLJ>
    </particlesLJ>

</input>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/XMLinputFiles/RayleighTaylor_large.xml
<?xml version="1.0"?>
<input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../XML_Parser/input.xsd">

    <generalParams>
        <t_end>0.5</t_end>
        <delta_t>0.0005</delta_t>
        <writeFrequency>100000</writeFrequency>
        <dimensionType>2D</dimensionType>

        <g_grav>-12.44</g_grav>
        <useGravity>yes</useGravity>

        <calcType>LJ</calcType>
        <baseNameOutputFiles>RayleighTaylor_large</baseNameOutputFiles>
        <particleContainerType>linkedCell</particleContainerType>
        <cutoffRadius>3.0</cutoffRadius>
        <gravInput>../eingabe-sonne.txt</gravInput>

        <loadCheckpoint>no</loadCheckpoint>
        <makeCheckpoint>no</makeCheckpoint>
        <pathInCheckpoint>checkpoint_FallingDropLiquid_fluid.txt</pathInCheckpoint>
        <pathOutCheckpoint>checkpoint_FallingDropLiquid_fluid.txt</pathOutCheckpoint>

        <domainSizeX>300</domainSizeX>
        <domainSizeY>54</domainSizeY>
        <domainSizeZ>0</domainSizeZ>

        <useThermostat>yes</useThermostat>
        <useBrownianMotion>yes</useBrownianMotion>
        <T_init>40</T_init>
        <T_target>40</T_target>
        <delta_T>-1</delta_T>
        <n_thermostat>1000</n_thermostat>
    </generalParams>

    <boundaryConditions>
        <top>outflowType</top>
        <right>outflowType</right>
        <bottom>outflowType</bottom>
        <left>outflowType</left>
        <front>outflowType</front>
        <back>outflowType</back>
    </boundaryConditions>

    <particlesLJ>
        <body>
            <bodyType>Cuboid</bodyType>
            <position>0.6,2,0</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>250,20,1</objectSpecificFormat>
            <epsilon>1.0</epsilon>
            <mass>1.0</mass>
            <rho>1.2</rho>
            <h>1.2</h>
        </body>

        <body>
            <bodyType>Cuboid</bodyType>
            <position>0.6,27,0</position>
            <velocity>0,0,0</velocity>
            <objectSpecificFormat>250,20,1</objectSpecificFormat>
            <epsilon>1.0</epsilon>
            <mass>2.0</mass>
            <rho>1.1</rho>
            <h>1.2</h>
        </body>
    </particlesLJ>

</input>
