=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/Example_Tree_Parser/people.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="gender_t">
        <xs:restriction base="xs:string">
            <xs:enumeration value="male"/>
            <xs:enumeration value="female"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="person_t">
        <xs:sequence>
            <xs:element name="first-name" type="xs:string"/>
            <xs:element name="middle-name" type="xs:string" minOccurs="0"/>
            <xs:element name="last-name" type="xs:string"/>
            <xs:element name="gender" type="gender_t"/>
            <xs:element name="age" type="xs:short"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <xs:complexType name="people_t">
        <xs:sequence>
            <xs:element name="person" type="person_t" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="people" type="people_t"/>

</xs:schema>

=== ThomasSedlmeyr/PSEMolDyn_GroupG/src/Example_Tree_Parser/people.xml
<?xml version="1.0"?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="people.xsd">

    <person id="1">
        <first-name>John</first-name>
        <last-name>Doe</last-name>
        <gender>male</gender>
        <age>32</age>
    </person>

    <person id="2">
        <first-name>Jane</first-name>
        <middle-name>Mary</middle-name>
        <last-name>Doe</last-name>
        <gender>female</gender>
        <age>28</age>
    </person>

</people>
